export default {
  ARCH: 'Architecture',
  LGHT: 'Lighting',
  BMED: 'Biomedical Engineering',
  CHME: 'Chemical Engineering',
  CIVL: 'Civil Engineering',
  ECSE: 'Electrical, Computer, and Systems Engineering',
  ENGR: 'General Engineering',
  ENVE: 'Environmental Engineering',
  ISYE: 'Industrial and Systems Engineering',
  MANE: 'Mechanical, Aerospace, and Nuclear Engineering',
  MTLE: 'Materials Science and Engineering',
  ARTS: 'Arts',
  COMM: 'Communication',
  IHSS: 'Interdisciplinary Studies',
  LANG: 'Foreign Languages',
  LITR: 'Literature',
  PHIL: 'Philosophy',
  STSH: 'Science and Technology Studies (Humanities Courses)',
  WRIT: 'Writing',
  COGS: 'Cognitive Science',
  ECON: 'Economics',
  GSAS: 'Games Simulation Arts and Sciences',
  PSYC: 'Psychology',
  STSS: 'Science and Technology Studies (Social Sciences Courses)',
  ITWS: 'Information Technology and Web Science',
  MGMT: 'Management',
  ASTR: 'Astronomy',
  BCBP: 'Biochemistry and Biophysics',
  BIOL: 'Biology',
  CHEM: 'Chemistry',
  CSCI: 'Computer Science',
  ISCI: 'Interdisciplinary Science',
  ERTH: 'Earth and Environmental Science',
  MATH: 'Mathematics',
  MATP: 'Mathematical Programming, Probability, and Statistics',
  PHYS: 'Physics',
  IENV: 'Interdisciplinary Environmental Courses',
  USAF: 'Aerospace Studies (Air Force ROTC)',
  USAR: 'Military Science (Army ROTC)',
  USNA: 'Naval Science (Navy ROTC)'
}
